name: Vercel Preview Deployment

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
      
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Build Project Artifacts
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Deploy to Vercel Preview
      id: vercel-deploy
      run: |
        DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
        echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_OUTPUT
        echo "deploy_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
        
    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🚀 Preview Deployment Ready!
            
            **Deploy URL:** ${{ steps.vercel-deploy.outputs.deploy_url }}
            
            ✅ Build completed successfully
            📦 Deployed via GitHub Actions
            🔄 This deployment bypassed Vercel's rate limits
            
            ---
            *Deployed from commit: ${context.sha.substring(0, 7)}*`
          })
          
    - name: Update status
      run: |
        echo "🚀 Preview deployment completed!"
        echo "🔗 Preview URL: ${{ steps.vercel-deploy.outputs.deploy_url }}"
        echo "💬 PR comment posted with deployment details" 